# Generated by Django 3.1.2 on 2020-12-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20201216_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
