# Generated by Django 3.1.2 on 2020-10-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_product_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('buying_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
