# Generated by Django 3.1.2 on 2020-11-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
